image: alpine

pages:
  script:
  - apk --no-cache add python3 python3-dev
  - pip3 install virtualenv
  - virtualenv -p python3 .
  - source bin/activate
  - pip3 install sphinx
  - pip3 install sphinx_rtd_theme
  - apk --no-cache add make
  - (cd doc && make html)
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master