image: alpine

pages:
  script:
  - apk --no-cache add py3-pip python-dev
  - pip install virtualenv
  - pip install sphinx
  - virtualenv -p python3 .
  - source bin/activate
  - pip install -r requirements.txt
  - apk --no-cache add make
  - (cd doc && make html)
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master